categories: [
  { name: 'Diet Centers',name_ar: 'مراكز الحميةالغذائية',value:'Diet Centers',img:'Diet Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Supplements',name_ar: 'المكملات الغذائية',value:'Supplements',img:'Supplements.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Dietary Consultants',name_ar: 'استشارات غذائية',value:'Dietary Consultants',img:'Dietary Consultants.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Injury Rehabilitation Centers',name_ar: 'مراكز تأهيل الإصابات الرياضية',value:'Sports Injury Rehabilitation Centers',img:'Sports Injury Rehabilitation Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Home Gym Equip. Providers',name_ar: 'معدات رياضية منزلية. مقدمي الخدمات',value:'Home Gym Equip. Providers',img:'Home GYM Equipment Providers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Gym Facilities',name_ar: 'معدات الصالة الرياضية',value:'Gym Facilities',img:'GYM Facilities.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Meditation & Yoga Centers',name_ar: 'مراكز التأمل واليوجا',value:'Meditation & Yoga Centers',img:'Meditation and Yoga Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Health Tours & Travel',name_ar: 'الرحلات الصحية والسفر',value:'Health Tours & Travel',img:'Health Tours and Travel.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Apparel for Adults & Kids',name_ar: 'الملابس الرياضية للبالغين والأطفال',value:'Sports Apparel for Adults & Kids',img:'Sports Apparel For Adults and Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Tech Companies',name_ar: 'شركات التقنية الرياضية',value:'Sports Tech Companies',img:'Sports Tech Companies.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Insurance Companies',name_ar: 'شركات التأمين',value:'Insurance Companies',img:'Insurance Companies.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Psychological Consultants',name_ar: 'المستشارين النفسيين',value:'Psychological Consultants',img:'Psychological Consultants.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Physiotherapy Centers',name_ar: 'مراكز العلاج الطبيعي',value:'Physiotherapy Centers',img:'Physiotherapy Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Wellness Services for Adults & Kids',name_ar: 'خدمات الصحية للبالغين والأطفال',value:'Wellness Services for Adults & Kids',img:'Wellness Services for Adults & Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Kids Nutrition Services',name_ar: 'خدمات التغذية للأطفال',value:'Kids Nutrition Services',img:'Kids Nutrition Services.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'After-school Actvities for Kids',name_ar: 'أنشطة ما بعد المدرسة للأطفال',value:'After-school Actvities for Kids',img:'After-school Activities for Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Wellness Products',name_ar: 'المنتجات الصحية',value:'Wellness Products',img:'Wellness Products.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Hygiene',name_ar: 'الصحة العامة',value:'Hygiene',img:'Hygiene.png' ,fullTitle:true,fullTitle_ar:true},

  { name: 'Alternative Medicine',name_ar: 'الطب البديل',value:'Alternative Medicine',img:'Alternative Medicine.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Women’s Health Services and Products',name_ar: 'خدمات ومنتجات صحة المرأة',value:'Women’s Health Services and Products',img:'WomenHealth.png',fullTitle:true,fullTitle_ar:true},
  ],



//------------------------------------------------------- AR -------------------------------------------------//

categories_ar:  [
  { name: 'Diet Centers',name_ar: 'مراكز الحميةالغذائية',value:'Diet Centers',img:'Diet Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Supplements',name_ar: 'المكملات الغذائية',value:'Supplements',img:'Supplements.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Dietary Consultants',name_ar: 'استشارات غذائية',value:'Dietary Consultants',img:'Dietary Consultants.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Injury Rehabilitation Centers',name_ar: 'مراكز تأهيل الإصابات الرياضية',value:'Sports Injury Rehabilitation Centers',img:'Sports Injury Rehabilitation Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Home Gym Equip. Providers',name_ar: 'معدات رياضية منزلية. مقدمي الخدمات',value:'Home Gym Equip. Providers',img:'Home GYM Equipment Providers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Gym Facilities',name_ar: 'معدات الصالة الرياضية',value:'Gym Facilities',img:'GYM Facilities.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Meditation & Yoga Centers',name_ar: 'مراكز التأمل واليوجا',value:'Meditation & Yoga Centers',img:'Meditation and Yoga Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Health Tours & Travel',name_ar: 'الرحلات الصحية والسفر',value:'Health Tours & Travel',img:'Health Tours and Travel.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Apparel for Adults & Kids',name_ar: 'الملابس الرياضية للبالغين والأطفال',value:'Sports Apparel for Adults & Kids',img:'Sports Apparel For Adults and Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Sports Tech Companies',name_ar: 'شركات التقنية الرياضية',value:'Sports Tech Companies',img:'Sports Tech Companies.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Insurance Companies',name_ar: 'شركات التأمين',value:'Insurance Companies',img:'Insurance Companies.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Psychological Consultants',name_ar: 'المستشارين النفسيين',value:'Psychological Consultants',img:'Psychological Consultants.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Physiotherapy Centers',name_ar: 'مراكز العلاج الطبيعي',value:'Physiotherapy Centers',img:'Physiotherapy Centers.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Wellness Services for Adults & Kids',name_ar: 'خدمات الصحية للبالغين والأطفال',value:'Wellness Services for Adults & Kids',img:'Wellness Services for Adults & Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Kids Nutrition Services',name_ar: 'خدمات التغذية للأطفال',value:'Kids Nutrition Services',img:'Kids Nutrition Services.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'After-school Actvities for Kids',name_ar: 'أنشطة ما بعد المدرسة للأطفال',value:'After-school Actvities for Kids',img:'After-school Activities for Kids.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Wellness Products',name_ar: 'المنتجات الصحية',value:'Wellness Products',img:'Wellness Products.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Hygiene',name_ar: 'الصحة العامة',value:'Hygiene',img:'Hygiene.png' ,fullTitle:true,fullTitle_ar:true},

  { name: 'Alternative Medicine',name_ar: 'الطب البديل',value:'Alternative Medicine',img:'Alternative Medicine.png' ,fullTitle:true,fullTitle_ar:true},
  { name: 'Women’s Health Services and Products',name_ar: 'خدمات ومنتجات صحة المرأة',value:'Women’s Health Services and Products',img:'WomenHealth.png',fullTitle:true,fullTitle_ar:true},
  ],
